#!/usr/bin/env python3
"""Extract the config blocks the Full installer deploys from the manual deployment guides,
so the automated and the manual path cannot drift apart.

Writes installer/orcastra_full_install/_blocks.py. tools/check_full_assets.py re-runs the
extraction and fails when the committed module differs from the docs.

  python3 installer/tools/gen_full_blocks.py
"""
import json
import os
import re
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(REPO, "docs", "deployment")
OUT = os.path.join(os.path.dirname(HERE), "orcastra_full_install", "_blocks.py")

_HEREDOC = re.compile(r"^\s*cat > (\S+) << ?'?(\w+)'?\s*$")
_FENCE = re.compile(r"^(\s*)```(\w*)\s*$")


def read(name: str) -> str:
    with open(os.path.join(DOCS, name), encoding="utf-8") as fh:
        return fh.read()


def heredocs(text: str) -> dict:
    """Map target path -> body for every `cat > PATH << 'TAG'` heredoc. The first heredoc
    for a path wins: later ones belong to optional steps (vm3 Step 13 rewrites
    roles_mapping.yml for SSO)."""
    out, lines, i = {}, text.splitlines(), 0
    while i < len(lines):
        m = _HEREDOC.match(lines[i])
        if not m:
            i += 1
            continue
        target, tag, body = m.group(1), m.group(2), []
        i += 1
        while i < len(lines) and lines[i].strip() != tag:
            body.append(lines[i])
            i += 1
        out.setdefault(target, "\n".join(body) + "\n")
        i += 1
    return out


def fences(text: str) -> list:
    """Every fenced block in the document as (start_line, lang, dedented body), paired from
    the top so a closing fence is never mistaken for an opening one."""
    out, lines, i = [], text.splitlines(), 0
    while i < len(lines):
        m = _FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        indent, body, j = m.group(1), [], i + 1
        while j < len(lines) and lines[j].strip() != "```":
            body.append(lines[j][len(indent):] if lines[j].startswith(indent) else lines[j])
            j += 1
        out.append((i, m.group(2), textwrap.dedent("\n".join(body)) + "\n"))
        i = j + 1
    return out


def fence_after(text: str, anchor: str, lang: str) -> str:
    """Body of the first ```lang fence that opens after the line containing `anchor`."""
    at = next(i for i, l in enumerate(text.splitlines()) if anchor in l)
    for start, flang, body in fences(text):
        if start > at and flang == lang:
            return body
    raise ValueError(f"no ```{lang} fence after {anchor!r}")


def opensearch_puts(text: str) -> list:
    """Every `$OS/<path> -X PUT ... -d '<json>'` command in document order (a block may hold
    several), as [path, parsed body]. The fluentbit user (a generated password) and the
    replica loop (run with the admin certificate) are done by the installer itself."""
    out = []
    call = re.compile(r"^\$OS/(\S+) -X PUT .*?-d '(.*?\n\})'", re.S | re.M)
    for _, lang, body in fences(text):
        if lang != "bash":
            continue
        for m in call.finditer(body):
            path = m.group(1)
            if path.startswith("_plugins/_security"):
                continue
            out.append([path, json.loads(m.group(2).replace("'\\''", "'"))])
    return out


def extract() -> dict:
    vm2, vm3, vm4 = read("vm2-vault.md"), read("vm3-opensearch.md"), read("vm4-dashboard.md")
    h3 = heredocs(vm3)
    blocks = {
        "VAULT_POLICY": heredocs(vm2)["/tmp/orcastra-policy.hcl"],
        "VAULT_LOGROTATE": fence_after(vm2, "Create `/etc/logrotate.d/vault-audit`", ""),
        "VAULT_FLUENTBIT_CONF": fence_after(vm2, "Edit `/etc/fluent-bit/fluent-bit.conf`", "ini"),
        "VAULT_FLUENTBIT_PARSER": fence_after(vm2, "Edit `/etc/fluent-bit/parsers.conf`", "ini"),
        "OS_ENV": h3[".env"],
        "OS_COMPOSE": h3["docker-compose.yml"],
        "OS_YML": h3["config/opensearch.yml"],
        "OS_INTERNAL_USERS": h3["config/internal_users.yml"],
        "OS_ROLES": h3["config/roles.yml"],
        "OS_ROLES_MAPPING": h3["config/roles_mapping.yml"],
        "OSD_YML": h3["config/opensearch_dashboards.yml"],
        "OS_API": opensearch_puts(vm3),
        "CMP_FLUENTBIT_CONF": fence_after(vm4, "Create `config/fluent-bit/fluent-bit.conf`", "ini"),
        "CMP_FLUENTBIT_PARSERS": fence_after(vm4, "Create `config/fluent-bit/parsers.conf`", "ini"),
        "CMP_ENV": fence_after(vm4, "nano .env", "ini"),
    }
    return blocks


def render_module(blocks: dict) -> str:
    out = ['"""GENERATED by tools/gen_full_blocks.py from docs/deployment/vm2..vm4 - do not edit.',
           "", "Re-generate after changing those guides, then run tools/check_full_assets.py.", '"""',
           "import json as _json", ""]
    for name, value in blocks.items():
        if isinstance(value, str):
            out.append(f"{name} = {json.dumps(value, ensure_ascii=False)}")
        else:
            out.append(f"{name} = _json.loads({json.dumps(json.dumps(value, ensure_ascii=False))})")
        out.append("")
    return "\n".join(out)


def main() -> None:
    module = render_module(extract())
    if "--stdout" in sys.argv:
        print(module)
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(module)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
