#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  install.sh --api-url <url> --enrollment-token <token> --agent-name <name> --frpc-token <token> --cluster-id <id> [--output <path>]

Required flags:
  --api-url            OrcaHub API base URL (ex; https://api.orcahub.example)
  --enrollment-token   Agent enrollment token
  --agent-name         Agent hostname/display name
  --frpc-token         FRPC auth token
  --cluster-id         Orcastra cluster identifier

Optional flags:
  --output             Output env file path (default: /etc/orca-agent/setup.env)
  -h, --help           Show this help
USAGE
}

require_value() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "error: missing required value for $name" >&2
    usage
    exit 1
  fi
}

escape_squote() {
  local input="$1"
  printf "%s" "$input" | sed "s/'/'\"'\"'/g"
}

API_URL=""
ENROLLMENT_TOKEN=""
AGENT_NAME=""
FRPC_TOKEN=""
CLUSTER_ID=""
OUTPUT_PATH="/etc/orca-agent/setup.env"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-url)
      API_URL="${2:-}"
      shift 2
      ;;
    --enrollment-token)
      ENROLLMENT_TOKEN="${2:-}"
      shift 2
      ;;
    --agent-name)
      AGENT_NAME="${2:-}"
      shift 2
      ;;
    --frpc-token)
      FRPC_TOKEN="${2:-}"
      shift 2
      ;;
    --cluster-id)
      CLUSTER_ID="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown flag '$1'" >&2
      usage
      exit 1
      ;;
  esac
done

require_value "--api-url" "$API_URL"
require_value "--enrollment-token" "$ENROLLMENT_TOKEN"
require_value "--agent-name" "$AGENT_NAME"
require_value "--frpc-token" "$FRPC_TOKEN"
require_value "--cluster-id" "$CLUSTER_ID"

case "$API_URL" in
  http://*|https://*) ;;
  *)
    echo "error: --api-url must start with http:// or https://" >&2
    exit 1
    ;;
esac

OUTPUT_DIR="$(dirname "$OUTPUT_PATH")"
mkdir -p "$OUTPUT_DIR"
umask 077

cat >"$OUTPUT_PATH" <<ENVFILE
# Generated by orcastra-docs/scripts/orca-agent/install.sh
# Keep this file private. It contains sensitive tokens.
ORCAHUB_API_URL='$(escape_squote "$API_URL")'
ORCA_AGENT_ENROLLMENT_TOKEN='$(escape_squote "$ENROLLMENT_TOKEN")'
ORCA_AGENT_NAME='$(escape_squote "$AGENT_NAME")'
ORCA_AGENT_FRPC_TOKEN='$(escape_squote "$FRPC_TOKEN")'
ORCA_AGENT_CLUSTER_ID='$(escape_squote "$CLUSTER_ID")'
ENVFILE

chmod 600 "$OUTPUT_PATH"

echo "ORCA Agent setup file created: $OUTPUT_PATH"
echo "Permissions: $(stat -c '%a' "$OUTPUT_PATH")"
echo ""
echo "Next steps:"
echo "1. Review values in the file and confirm they are correct."
echo "2. Load variables in your shell:"
echo "   set -a && source '$OUTPUT_PATH' && set +a"
echo "3. Continue with your ORCA agent register/run commands."
