[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
    HTTP_Server   Off

[INPUT]
    Name              tail
    Path              /vault/logs/audit.log
    Parser            json
    Tag               vault.audit
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On
    DB                /tmp/vault-audit.db

[OUTPUT]
    Name                opensearch
    Match               vault.audit
    Host                opensearch
    Port                9200
    tls                 On
    tls.verify          Off
    HTTP_User           fluentbit
    HTTP_Passwd         ${OPENSEARCH_FLUENTBIT_PASSWORD}
    Index               vault-audit
    Logstash_Format     On
    Logstash_Prefix     vault-audit
    Logstash_DateFormat %Y.%m.%d
    Suppress_Type_Name  On
    Retry_Limit         False
    Trace_Error         On
